# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a6740fb6c232647e6a69b648de3b2537d52c75542bd67dab853045234977ab711913e30f34d5370408da8ffb7f58f226fe6e79df08b5367024c4f682830c98

test:
  secret_key_base: ad359f36c064c74a1f44c5d9e12e8314bb89efadb6b27c05603cd9b3f862c768384ba6789c15bc0074e41f6842d7356a5971a339d11dbc7fb4dbef1cce046920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
