class TwitterProfile
  include ActiveModel::Model
  attr_accessor :screen_name, :real_name, :profile_image

  def self.from_oauth(h)
    # Initalise a profile from the hash generated by omniauth-twitter.
    TwitterProfile.new({
      screen_name: h[:info][:nickname],
      real_name: h[:info][:name],
      profile_image: h[:info][:image],
    })
  end
end